spring:
  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.show_sql: true
      hibernate.connection.characterEncoding: utf8mb4
      hibernate.connection.CharSet: utf8mb4
      hibernate.connection.useUnicode: true
  datasource:
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/books-catalog"
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/books-catalog"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
server:
  port: 8082